spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/account_db?currentSchema=${CURRENT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: ${CURRENT_SCHEMA}
